import React, { useState } from 'react';
import { CheckCircleIcon, FileTextIcon } from 'lucide-react';
const DocumentGenerator = ({
  patient
}) => {
  const [generatedContent, setGeneratedContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [documentType, setDocumentType] = useState('progress');
  const documentTypes = [{
    id: 'progress',
    name: 'Progress Report',
    description: 'Summary of patient recovery progress'
  }, {
    id: 'followup',
    name: 'Follow-up Instructions',
    description: 'Detailed care instructions for the patient'
  }, {
    id: 'referral',
    name: 'Specialist Referral',
    description: 'Referral to a specialist for further care'
  }, {
    id: 'discharge',
    name: 'Discharge Summary',
    description: 'Summary of care provided and discharge instructions'
  }];
  const handleGenerate = () => {
    setIsGenerating(true);
    // Simulate document generation
    setTimeout(() => {
      const mockContent = generateMockDocument(documentType, patient);
      setGeneratedContent(mockContent);
      setIsGenerating(false);
    }, 1500);
  };
  const generateMockDocument = (type, patient) => {
    switch (type) {
      case 'progress':
        return `
# Progress Report
**Patient:** ${patient.name} (${patient.id})
**Procedure:** ${patient.procedure}
**Date of Procedure:** ${patient.procedureDate}
**Report Date:** ${new Date().toLocaleDateString()}
## Current Status
Patient is currently experiencing significant pain (8/10) at the incision site with reported redness and swelling. Temperature is elevated at 100.2°F, suggesting possible infection.
## Vital Signs
- Temperature: 100.2°F
- Pulse: 88 bpm
- Respiration: 20 breaths/min
- Blood Pressure: 132/84 mmHg
- Pain Level: 8/10
## Medications
- Ibuprofen 600mg every 6 hours
- Oxycodone 5mg every 4-6 hours as needed for pain
- Cephalexin 500mg every 8 hours
## Recommendations
1. Immediate evaluation of incision site by physician
2. Consider adjustment to antibiotic regimen
3. Increase frequency of wound care and monitoring
4. Follow up appointment within 24 hours
## Generated by
Clinical Assistant System
${new Date().toLocaleString()}
        `;
      case 'followup':
        return `
# Follow-up Instructions
**Patient:** ${patient.name} (${patient.id})
**Procedure:** ${patient.procedure}
**Date of Procedure:** ${patient.procedureDate}
**Instructions Date:** ${new Date().toLocaleDateString()}
## Wound Care Instructions
1. Keep the incision clean and dry
2. Change dressing once daily using sterile technique
3. Monitor for increased redness, swelling, discharge, or opening of the incision
4. Do not submerge incision in water until cleared by your physician
## Medication Schedule
- Ibuprofen 600mg: Take every 6 hours with food
- Oxycodone 5mg: Take every 4-6 hours as needed for pain
- Cephalexin 500mg: Take every 8 hours until completed
## Activity Restrictions
1. No heavy lifting (>10 lbs) for 6 weeks
2. Gradually increase walking as tolerated
3. No driving while taking opioid pain medication
4. Return to work to be determined at follow-up appointment
## When to Seek Immediate Care
- Fever over 101°F
- Increasing pain not controlled by medication
- Redness, swelling, or discharge from incision site
- Shortness of breath or chest pain
- Severe headache or visual changes
## Follow-up Appointment
Please schedule a follow-up appointment within 7-10 days.
Contact: (555) 123-4567
## Generated by
Clinical Assistant System
${new Date().toLocaleString()}
        `;
      default:
        return `Document type not supported`;
    }
  };
  return <div className="max-w-4xl mx-auto">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-1">
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Document Type
              </label>
              <select value={documentType} onChange={e => setDocumentType(e.target.value)} className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500">
                {documentTypes.map(type => <option key={type.id} value={type.id}>
                    {type.name}
                  </option>)}
              </select>
              <p className="mt-1 text-xs text-gray-500">
                {documentTypes.find(t => t.id === documentType)?.description}
              </p>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Include Data
              </label>
              <div className="space-y-2">
                <div className="flex items-center">
                  <input id="vitals" type="checkbox" className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" defaultChecked />
                  <label htmlFor="vitals" className="ml-2 text-sm text-gray-700">
                    Vital Signs
                  </label>
                </div>
                <div className="flex items-center">
                  <input id="meds" type="checkbox" className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" defaultChecked />
                  <label htmlFor="meds" className="ml-2 text-sm text-gray-700">
                    Current Medications
                  </label>
                </div>
                <div className="flex items-center">
                  <input id="chat" type="checkbox" className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" defaultChecked />
                  <label htmlFor="chat" className="ml-2 text-sm text-gray-700">
                    Chat Assessment Data
                  </label>
                </div>
                <div className="flex items-center">
                  <input id="recommendations" type="checkbox" className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" defaultChecked />
                  <label htmlFor="recommendations" className="ml-2 text-sm text-gray-700">
                    Recommendations
                  </label>
                </div>
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Format
              </label>
              <div className="flex space-x-2">
                <button className="px-3 py-1.5 text-sm bg-blue-50 border border-blue-200 text-blue-700 rounded-md">
                  Markdown
                </button>
                <button className="px-3 py-1.5 text-sm bg-white border border-gray-300 text-gray-700 rounded-md">
                  PDF
                </button>
                <button className="px-3 py-1.5 text-sm bg-white border border-gray-300 text-gray-700 rounded-md">
                  DOCX
                </button>
              </div>
            </div>
            <button onClick={handleGenerate} disabled={isGenerating} className={`w-full py-2 rounded-md text-white font-medium ${isGenerating ? 'bg-gray-400' : 'bg-blue-600 hover:bg-blue-700'}`}>
              {isGenerating ? 'Generating...' : 'Generate Document'}
            </button>
          </div>
        </div>
        <div className="md:col-span-2">
          {isGenerating ? <div className="h-full flex flex-col items-center justify-center p-8 text-center">
              <div className="animate-pulse mb-4 h-8 w-8 rounded-full bg-blue-100 flex items-center justify-center">
                <FileTextIcon size={20} className="text-blue-600" />
              </div>
              <p className="text-gray-600">
                Analyzing patient data and generating document...
              </p>
              <p className="text-sm text-gray-500 mt-1">
                This may take a few moments
              </p>
            </div> : generatedContent ? <div className="border border-gray-200 rounded-lg p-4 h-full">
              <div className="flex justify-between items-center mb-4 pb-2 border-b border-gray-200">
                <div className="flex items-center">
                  <CheckCircleIcon size={16} className="text-green-600 mr-1" />
                  <span className="text-sm text-green-600 font-medium">
                    Document Generated
                  </span>
                </div>
                <div className="flex space-x-2">
                  <button className="px-2 py-1 text-xs bg-white border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50">
                    Edit
                  </button>
                  <button className="px-2 py-1 text-xs bg-blue-600 text-white rounded-md hover:bg-blue-700">
                    Save
                  </button>
                </div>
              </div>
              <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono p-2 h-[500px] overflow-y-auto">
                {generatedContent}
              </pre>
            </div> : <div className="h-full flex flex-col items-center justify-center p-8 border border-gray-200 border-dashed rounded-lg text-center">
              <div className="mb-4 h-12 w-12 rounded-full bg-gray-100 flex items-center justify-center">
                <FileTextIcon size={24} className="text-gray-400" />
              </div>
              <h3 className="text-gray-900 font-medium mb-1">
                No Document Generated
              </h3>
              <p className="text-gray-500 max-w-sm">
                Select a document type and click "Generate Document" to create
                an automated clinical document based on patient data.
              </p>
            </div>}
        </div>
      </div>
    </div>;
};
export default DocumentGenerator;